### ISSUE TITLE
추가

### ISSUE THREAD

**Issue by chrisKILee** [chrisKILee/chris#5]
5월 추가대행료 사유 추가
5월 지연 오더 회수

최근 이슈
로드샵 공유망 - 대표님이 배민원 이야기 나올때, 로드샵공유망에 대해서 다시 이야기 나옴 / 로드샵 요금제 커넥션이 가져가야한다. 스토어프로그램 통합 해야한다 , 머니서비스 있어야 한다. (전제) - 한다면 하반기 로 의견을 전달했지만.....
특정 B2B를 별도(주기) 정산 - 실시간 정산 아닌 주기정산 , 배경 : 요기배달, 배민원의 건수가 많아질때... 바로고가 안고가야하는 선지급이 많아짐.

**Comment by chrisKILee** [comment]
유플러스[강원정선허브]-MVNO check please : address are 2 / 강원 정선군 고한읍 고한리 65-10 고한주공아파트
유플러스[마산현동지사]-MVNO check please : address are 3 / 경남 창원시 마산합포구 현동 415
유플러스[삼척허브]-MVNO check please : address are 3 / 강원 삼척시 성내동 17-18

ST_CEO_SOCIAL_NUM must be string type

**Comment by chrisKILee** [comment]
python3 parser.py --op kcp --infile data/kcp_2023_2h.txt --outdir 2023_2H (25분)
python3 parser.py --op kicc --infile data/BAROGO1198-VAT-HALF.240104 --outdir 2023_2H(35분)

**Comment by chrisKILee** [comment]
Error saving credentials: error storing credentials - err: exit status 1, out: `Post "http://ipc/registry/credstore-updated": dial unix backend.sock: connect: no such file or directory`

**Comment by chrisKILee** [comment]
```
kubectl-argo-rollouts --namespace gorela-staging set image pos-server pos-server=653983231979.dkr.ecr.ap-northeast-2.amazonaws.com/barogo/dev-pos-server:0.7.39
Error: rollouts.argoproj.io "pos-server" is forbidden: User "system:anonymous" cannot get resource "rollouts" in API group "argoproj.io" in the namespace "gorela-staging"
```

**Comment by chrisKILee** [comment]
```
- name: staging-green
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - ap-northeast-2
      - eks
      - get-token
      - --cluster-name
      - staging-green-eks-cluster
      - --output
      - json
      - --role
      - arn:aws:iam::653983231979:role/custom_kubectl_gorela_user_role
      command: aws
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
```
